// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQRUUk7fssDSxIhraSfmg3grivxbiKXF4',
    appId: '1:375615416833:web:bb9b0cb02b43dfbb952e00',
    messagingSenderId: '375615416833',
    projectId: 'surfio-417b9',
    authDomain: 'surfio-417b9.firebaseapp.com',
    storageBucket: 'surfio-417b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO2VHK3hflKHaDxbfQuXY3Xb9vm2v-Y3M',
    appId: '1:375615416833:android:37fcfb619e0e3c7b952e00',
    messagingSenderId: '375615416833',
    projectId: 'surfio-417b9',
    storageBucket: 'surfio-417b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZbWwlYaID2VaMtUYFWlJPTnSJKmrRR4w',
    appId: '1:375615416833:ios:5253e7f1ec5d0cda952e00',
    messagingSenderId: '375615416833',
    projectId: 'surfio-417b9',
    storageBucket: 'surfio-417b9.appspot.com',
    iosBundleId: 'com.surfio.surfioMusicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQRUUk7fssDSxIhraSfmg3grivxbiKXF4',
    appId: '1:375615416833:web:3e7c622030acc38d952e00',
    messagingSenderId: '375615416833',
    projectId: 'surfio-417b9',
    authDomain: 'surfio-417b9.firebaseapp.com',
    storageBucket: 'surfio-417b9.appspot.com',
  );
}
